from numpy.fft import fft, ifft
from numpy import array, allclose, rint, zeros, reshape, roll, prod, sqrt, polymul, polydiv
from numpy.random import normal
from cyclo_primes_precomp import cyclo_primes
from math import pi, log
from cmath import exp
def primefac(n):
    """
    Computes the prime factorization of n.
    :param n: the positive integer to be factored
    :returns: the factorization as a list of (potentially repeated) primes
    """
    p = 2
    pfs = []
    while p**2 <= n:
        if (n % p):
            p += 1
        else:
            pfs.append(p)
            n = n//p
    if n > 1:
        pfs.append(n)
    return pfs

class Cyclotomic: 
    """
    A class providing numerical data and useful function relative to a Cyclotomic Number Field.
    """

    def __init__(self, cond, debug=False):
        """
        Initialize a Cyclotomic Number Field (denoted K) data and helping function:
        conductor (cond), degree (deg), discriminant (disc), cyclic_embedding, Trace, Norm,
        inner products (over K and Q), and construction of a Z-basis of the rank-1 
        module generated by a vector over OK.

        The Dedekind Zeta logderivative function requires precomputation from the 
        SageMath script "cyclo_primes.sage" stored in "cyclo_primes_precomp.py"

        :param cond: the conductor of the cyclotomic field (an integer != 2 modulo 4)
        :param debug: a debug bool, activating some extra checks at runtime
        """

        if cond%4 == 2:
            raise ValueError("There is no cyclotomic field of conductor c = 2 mod 4") 
        self.debug = debug
        self.cond = cond
        self.fact = primefac(cond)
        self.pfs = set(self.fact) # Prime factors
        self.expos = {f:self.fact.count(f) for f in self.pfs} # Exponents in the prime factorization


        # Euler's totient function to compute the degree
        self.deg = 1
        for p in self.pfs:
            self.deg *= (p-1) * p**(self.expos[p] - 1)

        # Discriminant computed following the Formula of Section 4.3, Theorem 8
        # Also to be found in [Was82, Proposition 2.7], or at
        # https://math.stackexchange.com/questions/2135290/disc-of-a-cyclotomic-field
        if self.deg==1:
            self.disc = 1
        else:
            self.disc = (-1)**(self.deg//2) * self.cond**self.deg
            for p in self.pfs:
                self.disc //= p**(self.deg//(p-1))

        self.nb_rootsofunity = 2*cond if (cond % 2) else cond
        self.nb_real_embeddings = 1 if self.deg==1 else 0
        self.nb_complex_embeddings = 0 if self.deg==1 else self.deg

        self.nonprimitiveroots = [i for i in range(cond) if not self.is_invertible_mod_cond(i)]
        self.primitiveroots = [i for i in range(cond) if self.is_invertible_mod_cond(i)]

        # Construct the Cyclic Embedding of 0 and 1
        self.zero = zeros(self.cond, dtype="int")
        self.one = self.cyclic_embedding([1]+(self.deg-1)*[0])
        pol = [1]
        w = exp(2j *pi / c)
        for i in self.primitiveroots:
            pol = polymul(pol, [1, -w**i])
        pol_ = array(rint(pol.real), dtype="int")
        assert(allclose(pol, pol_))
        self.defpoly = pol_

    def is_invertible_mod_cond(self, i):
        """
        A function testing whether an integer i is invertible modulo the conductor
        :param i: the integer to test
        :returns: a boolean
        """     
        for p in self.pfs:
            if not (i%p):
                return False
        return True

    def cyclic_embedding(self, x):
        """
        Compute the Cyclic Embedding of x (Section 3.3, Figure 3). 
        Input should have length K.deg or K.cond.
        :param x: an element of K, as an integer list or array of coefficients
        :returns: an element of the associated Cyclic Ring
        """     

        # Check Integrality
        if not allclose(x, rint(x)):
            raise ValueError("Input should be integral")

        # Check length, and convert input to an complex numpy array
        v = zeros(self.cond, dtype="complex128")
        if len(x) == self.deg:
            v[:self.deg] = x
        elif len(x) == self.cond:
            v[:] = x
        else:
            raise ValueError("Input should have length deg or cond")

        # The FFT computes all the embeddings (evaluation at primitive roots) but 
        # also evaluations at non primitive roots. Those will be cancelled out
        # to reach the Cyclic Embedding
        
        v  = fft(v)
        for i in self.nonprimitiveroots:
            v[i] = 0
        # Note the rescaling by cond to get an integral Cyclic Embedding
        v = self.cond * ifft(v)

        # Type conversion, and some debugging checks
        v_ = array(rint(v.real), dtype="int")
        assert(allclose(v, v_))
        if self.debug:
            self.check_cyclic_embedding(v)
        return v_

    def reduce_mod_defpoly(self, x):
        """
        Reduce modulo the defining polynomial of the field K. 
        Can be used to convert cyclic embedding to coefficient embedding.
        :param x: a polynomial, as an integer list or array of coefficients
        :returns: x modulo self.defpoly, as an array of length self.d
        """
        q, r = polydiv(x[::-1], self.defpoly)
        res = zeros(self.deg, dtype="int")
        res[:len(r)] = r[::-1]
        return res


    def spherical_sample(self, r, sigma = 100.):
        """
        Sample a spherically symmetric elements of K^r, represented in the 
        Cyclic Embedding. The output vector has length r*K.cond.
        :param r: rank over K of the element to be sampled
        :param sigma: (optional) Gaussian width of the element
        :returns: a spherically symmetric sample of K^r
        """     
        V = rint(normal(loc=0, scale=sigma, size=(r, self.cond)))
        return array([self.cyclic_embedding(v) for v in V]).flatten()

    def check_cyclic_embedding(self, v):
        """
        Check that a vector of length r*K.cond is indeed the Cyclic Embedding 
        of v ∈ K^r. Raise an error if not.
        :param v: the vector to be checked
        """     

        c, d = self.cond, self.deg
        if (len(v) % c):
            raise ValueError("len(v) (%d) is not a multiple of self.cond (%d)"%(len(v), c))
        for w in reshape(v, (len(v)//c, c)):
            u = fft(w)[self.nonprimitiveroots]
            if not allclose(u, 0*u):
                raise ValueError("Not the Cyclic Embedding of a cyclotomic vector")

    def complex_embeddings(self, x):
        """
        Return the list of complex embeddings of x ∈ K (Section 2.2)
        :param x: represented in the Cyclic Embedding
        """     
        c, d = self.cond, self.deg
        if (len(x) != c):
            raise ValueError("len(v) (%d) is not equal self.cond (%d)"%(len(v), c))
        if self.debug:
            self.check_cyclic_embedding(x)
        
        # The division by cond is here to compensate for a similar multiplication
        # done during the Cyclic Embedding to maintain integrality
        return fft(x)[self.primitiveroots] / self.cond

    def algebraic_norm(self, x):
        """
        Return the algebraic Norm N(x) of x ∈ K (Section 2.2)
        :param x: represented in the Cyclic Embedding
        "returns: the Algebraic Norm N(x) as a float"
        """     
        w = self.complex_embeddings(x)
        N = prod(w).real
        return N

    def trace(self, x):
        """
        Return the Trace Tr(x) of x ∈ K (Section 2.2)
        :param x: represented in the Cyclic Embedding
        "returns: the Algebraic Norm Tr(x) as a float"
        """
        w = self.complex_embeddings(x)
        tr = sum(w)
        tr_ = int(rint(tr.real))
        assert(allclose(tr, tr_))
        return tr_


    def ip_K(self, v, w):
        """
        Return the inner product over K <v, w>_K of v,w ∈ K^r (Section 2.2)
        :param v: v ∈ K^r, represented in the Cyclic Embedding
        :param w: w ∈ K^r, represented in the Cyclic Embedding
        "returns: the inner product <v, w>_K ∈ K, represented in the Cyclic Embedding
        """     
        c, d = self.cond, self.deg
        # Sanity-check the inputs
        if (len(v) % c):
            raise ValueError("len(v) (%d) is not a multiple of self.cond (%d)"%(len(v), c))
        if len(v) != len(w):
            raise ValueError("Dimension must match for inner products")
        if self.debug:
            self.check_cyclic_embedding(v)
            self.check_cyclic_embedding(w)

        ipe = zeros(self.cond, dtype="complex128")
        vb = reshape(v, (len(v)//c, c))
        wb = reshape(w, (len(w)//c, c))
        for i in range(len(v)//c):
            ipe += fft(vb[i]) * fft(wb[i]).conj()
        
        # Both v, and w have been scaled up by K.cond during Cyclic Embedding,
        # and must be compensated once by division for consistency.
        ipe /= self.cond
        ip = ifft(ipe)
        ip_ = array(rint(ip.real), dtype ="int")
        assert(allclose(ip, ip_))
        return ip_


    def ip_Q(self, v, w):
        """
        Return the inner product over Q <v, w> of v,w ∈ K^r (Section 2.2)
        :param v: v ∈ K^r, represented in the Cyclic Embedding
        :param w: w ∈ K^r, represented in the Cyclic Embedding
        "returns: the inner product <v, w> ∈ Q, as a float
        """     
        return self.trace(self.ip_K(v, w))

    def vOK_Zbasis(self, v):
        """
        Returns a Z-basis of the ideal v * O_K for an input vector v ∈ K^r.
        We here use the power-basis of cyclotomics: B = [v, v*X, v*X^2, ... , v*X^{deg-1}],
        and this guarentee is used to construct LWE samples.

        :param v: v ∈ K^r, represented in the Cyclic Embedding
        :returns: a list of K.deg elements of v ∈ K^r, reprensented in the Cyclic Embedding
        as a matrix of dimension K.deg x (r*K.cond)
        """     

        c, d = self.cond, self.deg
        if self.debug:
            self.check_cyclic_embedding(v)
        # In the cyclic embedding, multiplication by X is simply achieved by
        # rolling the coefficients
        return array([roll(reshape(v, (len(v)//c, c)), i, axis=1).flatten()
                      for i in range(d)])

    def logderivative_zeta(self, s):
        """
        Compute the logarithmic derivative of the Dedekind Zeta Function ζ'_K(s)/ζ_K(s) 
        (Section 4.5). This requires precomputation from the generated by a SageMath 
        script "cyclo_primes.sage" and stored in "cyclo_primes_precomp.py"
        :param s: a complex number
        "returns: 
        """    
        try:
            primes = cyclo_primes[self.cond]
        except:
            raise ValueError("Small primes list not precomputed for cyclotomic conductor %d"%self.cond)
        res = 0
        for p in primes:
            if p**s > 1e50:
                break
            res += log(p) / (1 - p**(s))
        return res

# Run some unit checks if not initialized from an import statement.
if __name__ == '__main__':
    for c in range(3, 40):
        if c%4 == 2:
            continue


        K = Cyclotomic(c, debug=True)
        
        X = K.cyclic_embedding([0,1]+(K.deg-2)*[0])
        one = K.cyclic_embedding([1]+(K.deg-1)*[0])
        # Do the cyclic convolution to compute the product, with adequate rescaling
        if K.deg > 3:
            X2 = K.cyclic_embedding([0,0,1]+(K.deg-3)*[0])
            X_2 = array(rint(ifft(fft(X)*fft(X)).real /K.cond), dtype ="int")
            # A check that the Cyclic Embedding if X squared is indeed
            # (a scaling of) the Cyclic Embedding of X^2
            assert((X2==X_2).all())

        # Check some algebraic norms
        assert(allclose(K.algebraic_norm(one), 1))
        assert(allclose(K.algebraic_norm(2*one), 2**K.deg))
        assert(allclose(K.algebraic_norm(X), 1))
        if K.deg > 3:
            assert(allclose(K.algebraic_norm(X2), 1))

        # If the conductor is prime power p^k, then the element 1-X should have
        # algebraic norm p
        if len(K.pfs)==1:
            assert(allclose(K.algebraic_norm(one - X), list(K.pfs)[0]))
        # And so should 1-X^2 if p is odd
        if len(K.pfs)==1 and (K.cond%2) and (K.deg > 3):
            assert(allclose(K.algebraic_norm(one - X2), list(K.pfs)[0]))

        # The trace of 1 is the degree, and other identities 
        assert(K.trace(one)==K.deg)
        assert((K.ip_K(one, one) == one).all())
        assert((K.ip_K(X, one) == X).all())

        # Check that reduce_mod_defpoly is the inverse of coefficient_embedding
        for test in range(10):
            x = K.spherical_sample(1, sigma=3)
            y = K.reduce_mod_defpoly(x)
            yy = K.reduce_mod_defpoly(y)
            assert((y==yy).all())
            xx = K.cyclic_embedding(y)//K.cond
            assert((x==xx).all())



    print("Cyclotomic tests all passed.")
